#!/usr/bin/env python3
"""
Regenerate the Blog Hub's "Latest Posts" card row from the posts actually
on disk, same philosophy as scripts/generate_sitemap.py: the filesystem is
the source of truth, so this can't drift from CONTENT-INDEX.md.

Caps at MAX_CARDS most recent posts (by Article schema datePublished).
Once more than MAX_CARDS posts exist, the oldest drops off automatically
to make room for the newest, keeping blog/index.html on a fixed rotation
instead of growing forever.

Only touches the block between the LATEST-POSTS-START/END markers in
blog/index.html. Everything else on the page (hero, category grid,
footer) is left untouched.

Run manually with: python3 scripts/generate_blog_hub_cards.py
Also run automatically on every push to main via
.github/workflows/update-sitemap.yml, alongside the sitemap generator.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_INDEX = REPO_ROOT / "blog" / "index.html"
MAX_CARDS = 9

START_MARKER = "<!-- LATEST-POSTS-START: auto-generated by scripts/generate_blog_hub_cards.py, do not hand-edit inside these markers -->"
END_MARKER = "<!-- LATEST-POSTS-END -->"


def find_posts():
    posts = []
    blog_dir = REPO_ROOT / "blog"
    for cat_dir in sorted(p for p in blog_dir.iterdir() if p.is_dir()):
        for post_dir in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
            post_index = post_dir / "index.html"
            if not post_index.exists():
                continue
            html = post_index.read_text(encoding="utf-8")

            headline = _extract(r'"headline":\s*"([^"]*)"', html)
            date_published = _extract(r'"datePublished":\s*"([^"]*)"', html)
            description = _extract(r'<meta name="description" content="([^"]*)"', html)
            img_block = _extract(r'class="post-featured-img"(.*?)>', html, flags=re.S)
            src = _extract(r'src="([^"]*)"', img_block or "")
            height = _extract(r'height="(\d+)"', img_block or "")
            alt = _extract(r'alt="([^"]*)"', img_block or "")

            if not all([headline, date_published, description, src, height, alt]):
                print(f"WARNING: skipping {post_index}, missing required field(s)", file=sys.stderr)
                continue

            base = re.sub(r"-1200w\.jpg$", "", Path(src).name)
            thumb_height = round(int(height) * 400 / 1200)

            posts.append({
                "headline": headline,
                "date": date_published,
                "description": description,
                "base": base,
                "thumb_height": thumb_height,
                "alt": alt,
                "category": cat_dir.name.capitalize(),
                "url": f"/blog/{cat_dir.name}/{post_dir.name}/index.html",
            })
    return posts


def _extract(pattern, text, flags=0):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else None


def render_card(p):
    base, cat, url = p["base"], p["category"], p["url"]
    return f'''        <div class="card post-card">
          <picture>
            <source type="image/webp" srcset="/images/blog/srcset/{base}-400w.webp 400w, /images/blog/srcset/{base}-800w.webp 800w" sizes="(max-width: 700px) 100vw, 33vw">
            <img class="post-thumb" src="/images/blog/srcset/{base}-400w.jpg"
              srcset="/images/blog/srcset/{base}-400w.jpg 400w, /images/blog/srcset/{base}-800w.jpg 800w"
              sizes="(max-width: 700px) 100vw, 33vw" width="400" height="{p['thumb_height']}" loading="lazy"
              alt="{p['alt']}">
          </picture>
          <div class="post-card-body">
            <span class="post-cat">{cat}</span>
            <h3>{p['headline']}</h3>
            <p>{p['description']}</p>
            <a class="cta" href="{url}">Read post</a>
          </div>
        </div>'''


def main():
    posts = find_posts()
    posts.sort(key=lambda p: p["date"], reverse=True)

    kept = posts[:MAX_CARDS]
    dropped = posts[MAX_CARDS:]

    grid = "\n      <div class=\"post-grid\">\n" + "\n".join(render_card(p) for p in kept) + "\n      </div>\n      "
    new_block = START_MARKER + grid + END_MARKER

    html = BLOG_INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    if not pattern.search(html):
        print("ERROR: LATEST-POSTS markers not found in blog/index.html", file=sys.stderr)
        return 1

    new_html = pattern.sub(lambda _: new_block, html, count=1)
    changed = new_html != html
    BLOG_INDEX.write_text(new_html, encoding="utf-8")

    print(f"Found {len(posts)} posts total. Showing {len(kept)} (cap {MAX_CARDS}).")
    for p in kept:
        print(f"  KEPT    {p['date']}  {p['headline']}")
    for p in dropped:
        print(f"  DROPPED {p['date']}  {p['headline']}")
    print("blog/index.html changed." if changed else "No changes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
