#!/usr/bin/env python3
"""
Regenerate each category hub's post listing from the posts actually on
disk. Same philosophy as scripts/generate_blog_hub_cards.py and
scripts/generate_sitemap.py: the filesystem is the source of truth.

Every hub now lists every post in its category — no rotating cap, no
noindexed "archive" overflow page. Categories that already had a 6-card
"latest" row (genres, artists, songs) keep that row as a featured strip
at the top, then a plain <a href> list of every post in the category
below it (title + one-line description, real anchor tags, not
JS-rendered, so it's crawlable regardless of script execution). Years
and Trivia never had that featured-row split, so they keep showing a
single full card grid, just generated instead of hand-maintained.

Pagination: if a category ever exceeds PAGINATE_THRESHOLD posts, the
hub page shows only the first PAGE_SIZE in its full list and additional
posts spill onto self-canonical, indexable /blog/<category>/page/N/
pages (not a noindex archive). No category is over the threshold today,
so this path is unexercised but present for when one is.

Years is sorted 1970 -> 1979 ascending (it's a complete, ordered decade
reference set, not a recency feed). Every other category sorts newest
first by Article schema datePublished.

Only touches the block between the CATEGORY-CARDS-START/END markers in
each blog/<category>/index.html, plus writes any /blog/<category>/page/N/
overflow pages. Everything else on a category page (intro, header,
footer) is left untouched.

Run manually with: python3 scripts/generate_category_cards.py
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "blog"
SITE = "https://musicofthe70s.net"

PAGE_SIZE = 100
PAGINATE_THRESHOLD = 100

# category folder name -> (display label, featured-row cap or None)
CATS = {
    "genres": ("Genres", 6),
    "artists": ("Artists", 6),
    "songs": ("Songs", 6),
    "trivia": ("Trivia", None),
    "years": ("Years", None),
}

# Sorted 1970 -> 1979 ascending instead of newest-first.
ASCENDING_CATS = {"years"}

START_MARKER = "<!-- CATEGORY-CARDS-START: auto-generated by scripts/generate_category_cards.py, do not hand-edit inside these markers -->"
END_MARKER = "<!-- CATEGORY-CARDS-END -->"


def _extract(pattern, text, flags=0):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else None


def find_posts(cat_dir: Path, cat_label: str, ascending: bool):
    posts = []
    for post_dir in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
        if post_dir.name == "archive":
            continue
        post_index = post_dir / "index.html"
        if not post_index.exists():
            continue
        html = post_index.read_text(encoding="utf-8")

        headline = _extract(r'"headline":\s*"([^"]*)"', html)
        date_published = _extract(r'"datePublished":\s*"([^"]*)"', html)
        description = _extract(r'<meta name="description" content="([^"]*)"', html)
        img_block = _extract(r'class="post-featured-img"(.*?)>', html, flags=re.S)
        src = _extract(r'src="([^"]*)"', img_block or "")
        height = _extract(r'height="(\d+)"', img_block or "")
        alt = _extract(r'alt="([^"]*)"', img_block or "")

        if not all([headline, date_published, description, src, height, alt]):
            print(f"WARNING: skipping {post_index}, missing required field(s)", file=sys.stderr)
            continue

        base = re.sub(r"-1200w\.jpg$", "", Path(src).name)
        thumb_height = round(int(height) * 400 / 1200)
        year_match = re.search(r"(\d{4})", post_dir.name)

        posts.append({
            "headline": headline,
            "date": date_published,
            "year": year_match.group(1) if year_match else "",
            "description": description,
            "base": base,
            "thumb_height": thumb_height,
            "alt": alt,
            "category": cat_label,
            "url": f"/blog/{cat_dir.name}/{post_dir.name}/",
        })

    if ascending:
        posts.sort(key=lambda p: p["year"])
    else:
        posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def render_card(p):
    base, cat, url = p["base"], p["category"], p["url"]
    return f'''        <div class="card post-card">
          <picture>
            <source type="image/webp" srcset="/images/blog/srcset/{base}-400w.webp 400w, /images/blog/srcset/{base}-800w.webp 800w" sizes="(max-width: 700px) 100vw, 33vw">
            <img class="post-thumb" src="/images/blog/srcset/{base}-400w.jpg"
              srcset="/images/blog/srcset/{base}-400w.jpg 400w, /images/blog/srcset/{base}-800w.jpg 800w"
              sizes="(max-width: 700px) 100vw, 33vw" width="400" height="{p['thumb_height']}" loading="lazy"
              alt="{p['alt']}">
          </picture>
          <div class="post-card-body">
            <span class="post-cat">{cat}</span>
            <h3>{p['headline']}</h3>
            <p>{p['description']}</p>
            <a class="cta" href="{url}">Read post</a>
          </div>
        </div>'''


def render_full_list(posts):
    items = "\n".join(
        f'          <li><a href="{p["url"]}">{p["headline"]}</a> &mdash; {p["description"]}</li>'
        for p in posts
    )
    return f'''<ul class="post-full-list">
{items}
        </ul>'''


def render_note(cat_name, cat_label, total, kept_count, split, page_count):
    if not split:
        return f'<div class="category-note">\n        <p>All <strong>{total} {cat_label}</strong> posts are shown above.</p>\n      </div>'

    status = (f"<p>Our {kept_count} latest {cat_label} posts are above. "
               f"Every {cat_label} post ({total} total) is listed below.</p>")
    if page_count > 1:
        status += (f'\n        <p>Showing the first {PAGE_SIZE}. '
                   f'<a href="/blog/{cat_name}/page/2/">See more {cat_label} &rarr;</a></p>')
    return f'<div class="category-note">\n        {status}\n      </div>'


def update_category_page(cat_name, cat_label, cap, posts):
    cat_index = BLOG_DIR / cat_name / "index.html"
    html = cat_index.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    if not pattern.search(html):
        print(f"ERROR: CATEGORY-CARDS markers not found in {cat_index}", file=sys.stderr)
        return False

    split = cap is not None and len(posts) > cap
    main_page_posts = posts[:PAGE_SIZE] if len(posts) > PAGINATE_THRESHOLD else posts
    page_count = 1 + max(0, (len(posts) - 1) // PAGE_SIZE) if len(posts) > PAGINATE_THRESHOLD else 1

    if split:
        kept = posts[:cap]
        grid = "\n      <div class=\"post-grid\">\n" + "\n".join(render_card(p) for p in kept) + "\n      </div>\n      "
        note = render_note(cat_name, cat_label, len(posts), len(kept), True, page_count)
        full_list = "\n      " + render_full_list(main_page_posts) + "\n      "
        new_block = START_MARKER + grid + note + full_list + END_MARKER
    else:
        grid = "\n      <div class=\"post-grid\">\n" + "\n".join(render_card(p) for p in posts) + "\n      </div>\n      "
        note = render_note(cat_name, cat_label, len(posts), len(posts), False, page_count)
        new_block = START_MARKER + grid + note + "\n      " + END_MARKER

    new_html = pattern.sub(lambda _: new_block, html, count=1)
    changed = new_html != html
    cat_index.write_text(new_html, encoding="utf-8")
    return changed


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZY77Y8DHV1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());

    gtag('config', 'G-ZY77Y8DHV1');
  </script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{label} &ndash; Page {page_num} | Music of the 70s Blog</title>
  <meta name="description" content="More {label_lower} posts on Music of the 70s, page {page_num} of {page_count}.">
  <link rel="canonical" href="{SITE}/blog/{cat_name}/page/{page_num}/">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <meta name="theme-color" content="#1a1a2e">

  <meta property="og:title" content="{label} &ndash; Page {page_num} | Music of the 70s Blog">
  <meta property="og:description" content="More {label_lower} posts on Music of the 70s, page {page_num} of {page_count}.">
  <meta property="og:url" content="{SITE}/blog/{cat_name}/page/{page_num}/">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Music of the 70s">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="site-logo"><span class="logo-vinyl">♪</span> Music of the 70s</a>
      <nav class="main-nav">
        <a href="/">Home</a>
        <a href="/#tools">Tools</a>
        <a href="/radio/">Listen Now</a>
        <a href="/pages/about">About</a>
        <a href="/blog/">Blog</a>
      </nav>
      <button class="nav-toggle" aria-label="Menu">☰</button>
    </div>
  </header>

  <main>
    <div class="container">
      <nav class="breadcrumb"><a href="/">Home</a> › <a href="/blog/">Blog</a> › <a href="/blog/{cat_name}/">{label}</a> › Page {page_num}</nav>

      <div class="page-intro">
        <h1>{label}: Page {page_num}</h1>
        <p>More {label_lower} posts, page {page_num} of {page_count}.</p>
      </div>

      <ul class="post-full-list">
{items}
      </ul>

      <p class="pagination-nav">
{prev_link}{next_link}      </p>
    </div>
  </main>

  <footer class="site-footer">
    <p>© 2026 Music of the 70s |
      <a href="/pages/privacy-policy">Privacy Policy</a> |
      <a href="/pages/terms-of-use">Terms of Use</a> |
      <a href="/pages/contact">Contact</a> |
      <a href="/pages/about">About</a> |
      <a href="/about/author/">About the Author</a> |
      <a href="/about/methodology/">How We Write</a>
    </p>
  </footer>

  <script src="/js/main.js"></script>
</body>
</html>
"""


def write_paginated_pages(cat_name, cat_label, posts):
    """Write /blog/<cat>/page/N/ for posts beyond PAGE_SIZE. No-op today
    (no category exceeds PAGINATE_THRESHOLD); exists so a category that
    grows past it gets real indexable pages instead of a noindex archive."""
    if len(posts) <= PAGINATE_THRESHOLD:
        return []

    overflow = posts[PAGE_SIZE:]
    chunks = [overflow[i:i + PAGE_SIZE] for i in range(0, len(overflow), PAGE_SIZE)]
    page_count = 1 + len(chunks)
    written = []

    for i, chunk in enumerate(chunks):
        page_num = i + 2
        page_dir = BLOG_DIR / cat_name / "page" / str(page_num)
        page_dir.mkdir(parents=True, exist_ok=True)
        items = "\n".join(
            f'        <li><a href="{p["url"]}">{p["headline"]}</a> &mdash; {p["description"]}</li>'
            for p in chunk
        )
        prev_num = page_num - 1
        prev_url = f"/blog/{cat_name}/" if prev_num == 1 else f"/blog/{cat_name}/page/{prev_num}/"
        prev_link = f'        <a href="{prev_url}">&larr; Newer {cat_label}</a>\n'
        next_link = ""
        if page_num < page_count:
            next_link = f'        <a href="/blog/{cat_name}/page/{page_num + 1}/">Older {cat_label} &rarr;</a>\n'

        html = PAGE_TEMPLATE.format(
            label=cat_label, label_lower=cat_label.lower(), cat_name=cat_name,
            page_num=page_num, page_count=page_count, items=items,
            prev_link=prev_link, next_link=next_link, SITE=SITE,
        )
        page_index = page_dir / "index.html"
        existing = page_index.read_text(encoding="utf-8") if page_index.exists() else None
        page_index.write_text(html, encoding="utf-8")
        written.append(page_index)
        if existing != html:
            print(f"WROTE {page_index.relative_to(REPO_ROOT)}")

    return written


def main():
    any_changed = False
    for cat_name, (cat_label, cap) in CATS.items():
        cat_dir = BLOG_DIR / cat_name
        ascending = cat_name in ASCENDING_CATS
        posts = find_posts(cat_dir, cat_label, ascending)

        page_changed = update_category_page(cat_name, cat_label, cap, posts)
        write_paginated_pages(cat_name, cat_label, posts)
        any_changed = any_changed or page_changed

        split = cap is not None and len(posts) > cap
        kept = posts[:cap] if split else posts
        print(f"\n=== {cat_label} (featured cap {cap}) ===")
        print(f"Found {len(posts)} posts total. Featured row shows {len(kept)}; full list shows all {len(posts)}.")
        print(f"blog/{cat_name}/index.html {'changed' if page_changed else 'unchanged'}.")

    return 0 if True else 1


if __name__ == "__main__":
    sys.exit(main())
