#!/usr/bin/env python3
"""
Regenerate each category page's capped card row, plus that category's full
archive page, from the posts actually on disk. Same philosophy as
scripts/generate_blog_hub_cards.py and scripts/generate_sitemap.py: the
filesystem is the source of truth.

Each category in CATS gets a real rotating cap: once more posts exist than
the cap, the oldest drop off the category page automatically (by Article
schema datePublished), same mechanic as the Blog Hub's 9-card Latest Posts
row. The category page also gets a nav note (total count, rotation note,
link to the archive) so a reader can never mistake the capped row for
everything that exists. The archive page always lists every post in that
category, uncapped, reverse chronological.

Years is intentionally NOT in CATS. It's a complete, ordered 1970-1979
reference set, not a rolling topic feed; a recency-based cap is the wrong
mechanic for it (Charlie's explicit call, 2026-08-16).

Only touches the block between the CATEGORY-CARDS-START/END markers in
each blog/<category>/index.html, plus fully (re)writes each
blog/<category>/archive/index.html. Everything else on a category page
(intro, header, footer) is left untouched.

Run manually with: python3 scripts/generate_category_cards.py
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "blog"

# category folder name -> (display label, cap). cap=None means uncapped
# (all posts shown, reverse chronological, no rotation-off).
CATS = {
    "genres": ("Genres", 6),
    "artists": ("Artists", 6),
    "songs": ("Songs", 6),
    "trivia": ("Trivia", None),  # no cap, Charlie-confirmed 2026-08-24
}

START_MARKER = "<!-- CATEGORY-CARDS-START: auto-generated by scripts/generate_category_cards.py, do not hand-edit inside these markers -->"
END_MARKER = "<!-- CATEGORY-CARDS-END -->"


def _extract(pattern, text, flags=0):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else None


def find_posts(cat_dir: Path, cat_label: str):
    posts = []
    for post_dir in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
        if post_dir.name == "archive":
            continue
        post_index = post_dir / "index.html"
        if not post_index.exists():
            continue
        html = post_index.read_text(encoding="utf-8")

        headline = _extract(r'"headline":\s*"([^"]*)"', html)
        date_published = _extract(r'"datePublished":\s*"([^"]*)"', html)
        description = _extract(r'<meta name="description" content="([^"]*)"', html)
        img_block = _extract(r'class="post-featured-img"(.*?)>', html, flags=re.S)
        src = _extract(r'src="([^"]*)"', img_block or "")
        height = _extract(r'height="(\d+)"', img_block or "")
        alt = _extract(r'alt="([^"]*)"', img_block or "")

        if not all([headline, date_published, description, src, height, alt]):
            print(f"WARNING: skipping {post_index}, missing required field(s)", file=sys.stderr)
            continue

        base = re.sub(r"-1200w\.jpg$", "", Path(src).name)
        thumb_height = round(int(height) * 400 / 1200)

        posts.append({
            "headline": headline,
            "date": date_published,
            "description": description,
            "base": base,
            "thumb_height": thumb_height,
            "alt": alt,
            "category": cat_label,
            "url": f"/blog/{cat_dir.name}/{post_dir.name}/index.html",
        })
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def render_card(p):
    base, cat, url = p["base"], p["category"], p["url"]
    return f'''        <div class="card post-card">
          <picture>
            <source type="image/webp" srcset="/images/blog/srcset/{base}-400w.webp 400w, /images/blog/srcset/{base}-800w.webp 800w" sizes="(max-width: 700px) 100vw, 33vw">
            <img class="post-thumb" src="/images/blog/srcset/{base}-400w.jpg"
              srcset="/images/blog/srcset/{base}-400w.jpg 400w, /images/blog/srcset/{base}-800w.jpg 800w"
              sizes="(max-width: 700px) 100vw, 33vw" width="400" height="{p['thumb_height']}" loading="lazy"
              alt="{p['alt']}">
          </picture>
          <div class="post-card-body">
            <span class="post-cat">{cat}</span>
            <h3>{p['headline']}</h3>
            <p>{p['description']}</p>
            <a class="cta" href="{url}">Read post</a>
          </div>
        </div>'''


def render_note(cat_name, cat_label, total, cap, kept_count):
    archive_url = f"/blog/{cat_name}/archive/index.html"
    if cap is not None and total > cap:
        status = (f"<p>Showing the {kept_count} most recent {cat_label} posts, "
                   f"out of <strong>{total} total</strong>. Cards rotate automatically "
                   f"as new posts are added, oldest off, newest on.</p>")
    else:
        status = f"<p>All <strong>{total} {cat_label}</strong> posts are shown below.</p>"
    return f'''<div class="category-note">
        {status}
        <p><a class="btn-secondary" href="{archive_url}">Browse the Full {cat_label} Archive →</a></p>
      </div>'''


def update_category_page(cat_name, cat_label, cap, posts):
    cat_index = BLOG_DIR / cat_name / "index.html"
    html = cat_index.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    if not pattern.search(html):
        print(f"ERROR: CATEGORY-CARDS markers not found in {cat_index}", file=sys.stderr)
        return False

    kept = posts if cap is None else posts[:cap]
    grid = "\n      <div class=\"post-grid\">\n" + "\n".join(render_card(p) for p in kept) + "\n      </div>\n      "
    note = render_note(cat_name, cat_label, len(posts), cap, len(kept))
    new_block = START_MARKER + grid + note + "\n      " + END_MARKER

    new_html = pattern.sub(lambda _: new_block, html, count=1)
    changed = new_html != html
    cat_index.write_text(new_html, encoding="utf-8")
    return changed


ARCHIVE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZY77Y8DHV1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());

    gtag('config', 'G-ZY77Y8DHV1');
  </script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{label} Archive | Music of the 70s Blog</title>
  <meta name="description" content="Every {label_lower} post on Music of the 70s, {total} total, newest first.">
  <link rel="canonical" href="https://musicofthe70s.net/blog/{cat_name}/archive/index.html">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <meta name="theme-color" content="#1a1a2e">

  <meta property="og:title" content="{label} Archive | Music of the 70s Blog">
  <meta property="og:description" content="Every {label_lower} post on Music of the 70s, {total} total, newest first.">
  <meta property="og:url" content="https://musicofthe70s.net/blog/{cat_name}/archive/index.html">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Music of the 70s">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <header class="site-header">
    <div class="header-inner">
      <a href="/index.html" class="site-logo"><span class="logo-vinyl">♪</span> Music of the 70s</a>
      <nav class="main-nav">
        <a href="/index.html">Home</a>
        <a href="/index.html#tools">Tools</a>
        <a href="/pages/about.html">About</a>
        <a href="/blog/index.html">Blog</a>
      </nav>
      <button class="nav-toggle" aria-label="Menu">☰</button>
    </div>
  </header>

  <main>
    <div class="container">
      <nav class="breadcrumb"><a href="/index.html">Home</a> › <a href="/blog/index.html">Blog</a> › <a href="/blog/{cat_name}/index.html">{label}</a> › Archive</nav>

      <div class="page-intro">
        <h1>{label} Archive</h1>
        <p>All {total} {label_lower} posts, newest first.</p>
      </div>

      <div class="post-grid">
{cards}
      </div>
    </div>
  </main>

  <footer class="site-footer">
    <p>© 2026 Music of the 70s |
      <a href="/pages/privacy-policy.html">Privacy Policy</a> |
      <a href="/pages/about.html">About</a>
    </p>
  </footer>

  <script src="/js/main.js"></script>
</body>
</html>
"""


def write_archive_page(cat_name, cat_label, posts):
    archive_dir = BLOG_DIR / cat_name / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)
    archive_index = archive_dir / "index.html"

    cards = "\n".join(render_card(p) for p in posts)
    html = ARCHIVE_TEMPLATE.format(
        label=cat_label, label_lower=cat_label.lower(), cat_name=cat_name,
        total=len(posts), cards=cards,
    )
    existing = archive_index.read_text(encoding="utf-8") if archive_index.exists() else None
    archive_index.write_text(html, encoding="utf-8")
    return existing != html


def main():
    any_changed = False
    for cat_name, (cat_label, cap) in CATS.items():
        cat_dir = BLOG_DIR / cat_name
        posts = find_posts(cat_dir, cat_label)
        kept = posts if cap is None else posts[:cap]
        dropped = [] if cap is None else posts[cap:]

        page_changed = update_category_page(cat_name, cat_label, cap, posts)
        archive_changed = write_archive_page(cat_name, cat_label, posts)
        any_changed = any_changed or page_changed or archive_changed

        print(f"\n=== {cat_label} (cap {cap}) ===")
        print(f"Found {len(posts)} posts total. Showing {len(kept)} on category page.")
        for p in kept:
            print(f"  KEPT    {p['date']}  {p['headline']}")
        for p in dropped:
            print(f"  DROPPED {p['date']}  {p['headline']} (still in archive)")
        print(f"blog/{cat_name}/index.html {'changed' if page_changed else 'unchanged'}.")
        print(f"blog/{cat_name}/archive/index.html {'changed' if archive_changed else 'unchanged'}.")

    return 0 if True else 1


if __name__ == "__main__":
    sys.exit(main())
