#!/usr/bin/env python3
"""
Regenerate the Blog Hub's "Latest Posts" card row from the posts actually
on disk, same philosophy as scripts/generate_sitemap.py: the filesystem is
the source of truth, so this can't drift from CONTENT-INDEX.md.

Caps at MAX_CARDS most recent posts (by Article schema datePublished).
Once more than MAX_CARDS posts exist, the oldest drops off automatically
to make room for the newest, keeping blog/index.html on a fixed rotation
instead of growing forever.

Also renders a nav note below the card row (real total post count across
every category, a rotation notice, and a link to /blog/archive/, the
site-wide archive listing every post ever published) and regenerates that
archive page itself. Same mechanic as scripts/generate_category_cards.py,
just at the whole-site level instead of per-category. Added 2026-08-16
after Charlie asked how a visitor reaches a post that's rotated off the
Hub — the per-category archives already covered that, but the Hub itself
had no equivalent "browse everything" link of its own.

Only touches the block between the LATEST-POSTS-START/END markers in
blog/index.html, plus fully (re)writes blog/archive/index.html.
Everything else on the Hub page (hero, category grid, footer) is left
untouched.

Run manually with: python3 scripts/generate_blog_hub_cards.py
Also run automatically on every push to main via
.github/workflows/update-sitemap.yml, alongside the sitemap generator.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "blog"
BLOG_INDEX = BLOG_DIR / "index.html"
ARCHIVE_INDEX = BLOG_DIR / "archive" / "index.html"
MAX_CARDS = 9

START_MARKER = "<!-- LATEST-POSTS-START: auto-generated by scripts/generate_blog_hub_cards.py, do not hand-edit inside these markers -->"
END_MARKER = "<!-- LATEST-POSTS-END -->"


def find_posts():
    posts = []
    for cat_dir in sorted(p for p in BLOG_DIR.iterdir() if p.is_dir()):
        for post_dir in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
            if post_dir.name == "archive":
                continue
            post_index = post_dir / "index.html"
            if not post_index.exists():
                continue
            html = post_index.read_text(encoding="utf-8")

            headline = _extract(r'"headline":\s*"([^"]*)"', html)
            date_published = _extract(r'"datePublished":\s*"([^"]*)"', html)
            description = _extract(r'<meta name="description" content="([^"]*)"', html)
            img_block = _extract(r'class="post-featured-img"(.*?)>', html, flags=re.S)
            src = _extract(r'src="([^"]*)"', img_block or "")
            height = _extract(r'height="(\d+)"', img_block or "")
            alt = _extract(r'alt="([^"]*)"', img_block or "")

            if not all([headline, date_published, description, src, height, alt]):
                print(f"WARNING: skipping {post_index}, missing required field(s)", file=sys.stderr)
                continue

            base = re.sub(r"-1200w\.jpg$", "", Path(src).name)
            thumb_height = round(int(height) * 400 / 1200)

            posts.append({
                "headline": headline,
                "date": date_published,
                "description": description,
                "base": base,
                "thumb_height": thumb_height,
                "alt": alt,
                "category": cat_dir.name.capitalize(),
                "url": f"/blog/{cat_dir.name}/{post_dir.name}/index.html",
            })
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def _extract(pattern, text, flags=0):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else None


def render_card(p):
    base, cat, url = p["base"], p["category"], p["url"]
    return f'''        <div class="card post-card">
          <picture>
            <source type="image/webp" srcset="/images/blog/srcset/{base}-400w.webp 400w, /images/blog/srcset/{base}-800w.webp 800w" sizes="(max-width: 700px) 100vw, 33vw">
            <img class="post-thumb" src="/images/blog/srcset/{base}-400w.jpg"
              srcset="/images/blog/srcset/{base}-400w.jpg 400w, /images/blog/srcset/{base}-800w.jpg 800w"
              sizes="(max-width: 700px) 100vw, 33vw" width="400" height="{p['thumb_height']}" loading="lazy"
              alt="{p['alt']}">
          </picture>
          <div class="post-card-body">
            <span class="post-cat">{cat}</span>
            <h3>{p['headline']}</h3>
            <p>{p['description']}</p>
            <a class="cta" href="{url}">Read post</a>
          </div>
        </div>'''


def render_note(total, kept_count):
    if total > MAX_CARDS:
        status = (f"<p>Showing the {kept_count} most recent posts, out of "
                   f"<strong>{total} total</strong> across every category. Cards rotate "
                   f"automatically as new posts are added, oldest off, newest on.</p>")
    else:
        status = f"<p>All <strong>{total} posts</strong> are shown below.</p>"
    return f'''<div class="category-note">
        {status}
        <p><a class="btn-secondary" href="/blog/archive/index.html">Browse the Full Blog Archive →</a></p>
      </div>'''


ARCHIVE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZY77Y8DHV1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());

    gtag('config', 'G-ZY77Y8DHV1');
  </script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog Archive | Music of the 70s</title>
  <meta name="description" content="Every post on the Music of the 70s blog, {total} total, newest first.">
  <link rel="canonical" href="https://musicofthe70s.net/blog/archive/index.html">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <meta name="theme-color" content="#1a1a2e">

  <meta property="og:title" content="Blog Archive | Music of the 70s">
  <meta property="og:description" content="Every post on the Music of the 70s blog, {total} total, newest first.">
  <meta property="og:url" content="https://musicofthe70s.net/blog/archive/index.html">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Music of the 70s">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <header class="site-header">
    <div class="header-inner">
      <a href="/index.html" class="site-logo"><span class="logo-vinyl">♪</span> Music of the 70s</a>
      <nav class="main-nav">
        <a href="/index.html">Home</a>
        <a href="/index.html#tools">Tools</a>
        <a href="/pages/about.html">About</a>
        <a href="/blog/index.html">Blog</a>
      </nav>
      <button class="nav-toggle" aria-label="Menu">☰</button>
    </div>
  </header>

  <main>
    <div class="container">
      <nav class="breadcrumb"><a href="/index.html">Home</a> › <a href="/blog/index.html">Blog</a> › Archive</nav>

      <div class="page-intro">
        <h1>Blog Archive</h1>
        <p>All {total} posts, newest first.</p>
      </div>

      <div class="post-grid">
{cards}
      </div>
    </div>
  </main>

  <footer class="site-footer">
    <p>© 2026 Music of the 70s |
      <a href="/pages/privacy-policy.html">Privacy Policy</a> |
      <a href="/pages/about.html">About</a>
    </p>
  </footer>

  <script src="/js/main.js"></script>
</body>
</html>
"""


def write_archive_page(posts):
    ARCHIVE_INDEX.parent.mkdir(parents=True, exist_ok=True)
    cards = "\n".join(render_card(p) for p in posts)
    html = ARCHIVE_TEMPLATE.format(total=len(posts), cards=cards)
    existing = ARCHIVE_INDEX.read_text(encoding="utf-8") if ARCHIVE_INDEX.exists() else None
    ARCHIVE_INDEX.write_text(html, encoding="utf-8")
    return existing != html


def main():
    posts = find_posts()

    kept = posts[:MAX_CARDS]
    dropped = posts[MAX_CARDS:]

    grid = "\n      <div class=\"post-grid\">\n" + "\n".join(render_card(p) for p in kept) + "\n      </div>\n      "
    note = render_note(len(posts), len(kept))
    new_block = START_MARKER + grid + note + "\n      " + END_MARKER

    html = BLOG_INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    if not pattern.search(html):
        print("ERROR: LATEST-POSTS markers not found in blog/index.html", file=sys.stderr)
        return 1

    new_html = pattern.sub(lambda _: new_block, html, count=1)
    hub_changed = new_html != html
    BLOG_INDEX.write_text(new_html, encoding="utf-8")

    archive_changed = write_archive_page(posts)

    print(f"Found {len(posts)} posts total. Showing {len(kept)} (cap {MAX_CARDS}).")
    for p in kept:
        print(f"  KEPT    {p['date']}  {p['headline']}")
    for p in dropped:
        print(f"  DROPPED {p['date']}  {p['headline']} (still in archive)")
    print("blog/index.html changed." if hub_changed else "blog/index.html unchanged.")
    print("blog/archive/index.html changed." if archive_changed else "blog/archive/index.html unchanged.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
