"""Shared JSON-LD constants and helpers for every script that writes or
checks schema: apply_schema.py, generate_category_cards.py,
generate_blog_hub_cards.py and check_schema.py.

The Organization and WebSite nodes are defined once, on the home page,
with the stable @ids below. The Person node is defined once, on
/about/author/. Every other page references those @ids. Posts also keep
name/url inline next to the @id, because Google's rich-result parser
reads each page on its own and does not follow an @id to another page.
"""
import html
import json
import re

SITE = "https://musicofthe70s.net"
SITE_NAME = "Music of the 70s"

ORG_ID = f"{SITE}/#organization"
WEBSITE_ID = f"{SITE}/#website"
AUTHOR_ID = f"{SITE}/about/author/"
AUTHOR_NAME = "Charlie"

LOGO = {
    "@type": "ImageObject",
    "url": f"{SITE}/favicon-512.png",
    "width": 512,
    "height": 512,
}

AUTHOR_REF = {
    "@type": "Person",
    "@id": AUTHOR_ID,
    "name": AUTHOR_NAME,
    "url": AUTHOR_ID,
}

PUBLISHER_REF = {
    "@type": "Organization",
    "@id": ORG_ID,
    "name": SITE_NAME,
    "url": f"{SITE}/",
    "logo": LOGO,
}

LD_RE = re.compile(r'(<script type="application/ld\+json">)(.*?)(</script>)', re.S)


def dump_block(data):
    """Serialize one JSON-LD block in the site's existing house style:
    2-space indent, the whole object indented 2 more inside the tag."""
    body = json.dumps(data, indent=2, ensure_ascii=False)
    return "\n" + "\n".join("  " + line for line in body.split("\n")) + "\n  "


def script_tag(data):
    return f'<script type="application/ld+json">{dump_block(data)}</script>'


def breadcrumb(crumbs):
    """crumbs: list of (name, absolute url)."""
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i, "name": name, "item": url}
            for i, (name, url) in enumerate(crumbs, 1)
        ],
    }


def collection_page(url, name, description, items):
    """Hub schema: CollectionPage whose mainEntity is an ItemList of the
    posts the hub actually lists. items: list of (headline, absolute url)."""
    return {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": url,
        "url": url,
        "name": name,
        "description": description,
        "isPartOf": {"@id": WEBSITE_ID},
        "publisher": {"@id": ORG_ID},
        "mainEntity": {
            "@type": "ItemList",
            "numberOfItems": len(items),
            "itemListElement": [
                {"@type": "ListItem", "position": i, "url": u, "name": n}
                for i, (n, u) in enumerate(items, 1)
            ],
        },
    }


def json_string(raw):
    """Decode a JSON string body pulled out of HTML by regex (handles
    escapes like \\u2019 so schema names match the visible text)."""
    return json.loads(f'"{raw}"')


def html_unescape(text):
    return html.unescape(text)


SCHEMA_START = "<!-- SCHEMA-START: auto-generated by {script}, do not hand-edit inside these markers -->"
SCHEMA_END = "<!-- SCHEMA-END -->"


def upsert_head_schema(page, script_name, blocks):
    """Replace (or insert before </head>) the marker-wrapped schema block."""
    start = SCHEMA_START.format(script=script_name)
    new = start + "\n  " + "\n  ".join(script_tag(b) for b in blocks) + "\n  " + SCHEMA_END
    pattern = re.compile(r"<!-- SCHEMA-START:.*?-->.*?" + re.escape(SCHEMA_END), re.S)
    if pattern.search(page):
        return pattern.sub(lambda _: new, page, count=1)
    return page.replace("</head>", "  " + new + "\n</head>", 1)


def page_meta(page):
    """Canonical URL, visible H1 text and meta description of a page, as
    plain text, so hub schema names/descriptions match what's on screen."""
    def grab(pattern):
        m = re.search(pattern, page, re.S)
        return html.unescape(re.sub(r"<[^>]+>", "", m.group(1))).strip() if m else None
    return (
        grab(r'<link rel="canonical" href="([^"]*)"'),
        grab(r"<h1[^>]*>(.*?)</h1>"),
        grab(r'<meta name="description" content="([^"]*)"'),
    )


def hub_schema_blocks(page, crumbs, posts):
    """CollectionPage + ItemList + BreadcrumbList for a hub page.
    posts: dicts with raw-JSON "headline" and site-relative "url", in the
    order the hub renders them."""
    url, name, description = page_meta(page)
    items = [(json_string(p["headline"]), SITE + p["url"]) for p in posts]
    return [collection_page(url, name, description, items), breadcrumb(crumbs)]
